[package]
name = "find_my_fav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.31.0"
glob = "0.3.0"
sdl2 = { version = "0.37.0", features = ["image"]}
rand = "0.9.0-alpha.1"